version: "3"
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    # イメージ名を指定
    image: atcoder-env

    # localとcontainer間のファイルを同期させる
    # ${local}:${container}
    volumes:
      - ../problems:/root/problems:cached
      - ../library:/root/library:cached
      - ../heuristic:/root/heuristic:cached
      - ../acc-template-python:/root/.config/atcoder-cli-nodejs/python:cached
      - ../acc-template-cpp:/root/.config/atcoder-cli-nodejs/cpp:cached
      - ../.vscode:/root/.vscode:cached
      # jupyterlabの永続化のための設定
      - ./root_jupyter:/root/.jupyter:cached

      # # オプション これらのconfigファイルが必要なければコメントアウト
      # - ../dotfiles/.zshrc:/root/.zshrc
      # - ../dotfiles/.zinit:/root/.zinit
      # - ../dotfiles/.zsh_history:/root/.zsh_history
      # - ../dotfiles/.aliases:/root/.aliases

    entrypoint: >
      jupyter-lab
      --allow-root
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --NotebookApp.token=''
    expose:
      - "8888"
    ports:
      - "8889:8888"
    working_dir: /root
    # Overrides default command so things don't shut down after the process ends.
    # 以下のコメントを解くと jupyter labが動かなくなる
    # command: /bin/sh -c "while sleep 1000; do :; done"
